"""associate user to team member

Revision ID: 0224beb857f7
Revises: 89fac7c8d13a
Create Date: 2022-02-27 14:10:10.422938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0224beb857f7'
down_revision = '89fac7c8d13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.add_column('feedback', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'user', ['user_id'], ['id'])
    op.add_column('feedback_tag_group', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedback_tag_group', 'user', ['user_id'], ['id'])
    op.add_column('team_member', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_team_member_email'), 'team_member', ['email'], unique=True)
    op.create_index(op.f('ix_team_member_uuid'), 'team_member', ['uuid'], unique=False)
    op.drop_index('ix_user_uuid', table_name='team_member')
    op.create_foreign_key(None, 'team_member', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_member', type_='foreignkey')
    op.create_index('ix_user_uuid', 'team_member', ['uuid'], unique=False)
    op.drop_index(op.f('ix_team_member_uuid'), table_name='team_member')
    op.drop_index(op.f('ix_team_member_email'), table_name='team_member')
    op.drop_column('team_member', 'user_id')
    op.drop_constraint(None, 'feedback_tag_group', type_='foreignkey')
    op.drop_column('feedback_tag_group', 'user_id')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'user_id')
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
