"""Adds team to pairing sessions

Revision ID: 0e1eeb911eea
Revises: b57757d7a6f3
Create Date: 2020-05-23 22:03:36.546115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1eeb911eea'
down_revision = 'b57757d7a6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairing_session', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pairing_session', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pairing_session', type_='foreignkey')
    op.drop_column('pairing_session', 'team_id')
    # ### end Alembic commands ###
