"""Adds user auth fields

Revision ID: 3a8d6da48365
Revises: 20bb8765477e
Create Date: 2021-03-06 10:03:52.863234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8d6da48365'
down_revision = '20bb8765477e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('full_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('password', sa.Text(), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'password')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
