"""Adds streak to pairing session

Revision ID: 878c8eaf1ad3
Revises: 8b5407837885
Create Date: 2020-06-21 14:22:08.229548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878c8eaf1ad3'
down_revision = '8b5407837885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairing_session', sa.Column('streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairing_session', 'streak')
    # ### end Alembic commands ###
