"""adds recuring_weekday to reminder

Revision ID: 8b5407837885
Revises: 75a24eaa9ee5
Create Date: 2020-06-14 20:08:43.318874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5407837885'
down_revision = '75a24eaa9ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('recuring_weekday', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminder', 'recuring_weekday')
    # ### end Alembic commands ###
